import { EventEmitter } from 'node:events'
import type { ErrorInfo, ProgressEvent } from '@shared/types'

export interface OperationHandle {
  id: string
  signal: AbortSignal
  progress(message: string, percent: number | null): void
}

/**
 * Tracks long-running operations (clone, scan, later fetch/rebase...) so the
 * status bar can show progress and the user can cancel them. Operation ids
 * are generated by the renderer so it can cancel before invoke() resolves.
 */
export class OperationManager extends EventEmitter<{ progress: [ProgressEvent] }> {
  private readonly running = new Map<string, { controller: AbortController; title: string; cancellable: boolean }>()
  private readonly lastEmit = new Map<string, number>()

  async run<T>(id: string, title: string, cancellable: boolean, fn: (op: OperationHandle) => Promise<T>): Promise<T> {
    if (this.running.has(id)) throw new Error(`Operation ${id} is already running`)
    const controller = new AbortController()
    this.running.set(id, { controller, title, cancellable })
    const base = { opId: id, title, cancellable }
    this.emit('progress', { ...base, message: 'Starting…', percent: null, done: false })
    const handle: OperationHandle = {
      id,
      signal: controller.signal,
      progress: (message, percent) => {
        // Throttle to ~20 updates/s; git can emit hundreds of progress lines per second.
        const now = Date.now()
        if (now - (this.lastEmit.get(id) ?? 0) < 50) return
        this.lastEmit.set(id, now)
        this.emit('progress', { ...base, message, percent, done: false })
      }
    }
    try {
      const result = await fn(handle)
      this.emit('progress', { ...base, message: 'Done', percent: 100, done: true })
      return result
    } catch (err) {
      const error: ErrorInfo =
        err && typeof err === 'object' && 'toInfo' in err && typeof err.toInfo === 'function'
          ? (err.toInfo() as ErrorInfo)
          : { message: err instanceof Error ? err.message : String(err), code: 'UNKNOWN' }
      this.emit('progress', { ...base, message: error.message, percent: null, done: true, error })
      throw err
    } finally {
      this.running.delete(id)
      this.lastEmit.delete(id)
    }
  }

  cancel(id: string): void {
    const op = this.running.get(id)
    if (op?.cancellable) op.controller.abort()
  }

  cancelAll(): void {
    for (const op of this.running.values()) op.controller.abort()
  }
}
